# 잇다 — 사용자 여정과 그때 도는 코드

**「무엇을 썼다」가 아니라 「언제 무엇이 도는가」를 적는다.**
기술 목록은 `기술스택_잇다.md`, 측정치는 `실측기록_잇다.md`.
세 문서는 **같은 용어·같은 개수**를 쓴다. 어긋나면 코드가 정답이다.

2026-08-06 코드 전수 재확인.

---

# 제0부 — 읽는 법

이 문서는 **시간 순**이다. 사용자가 첫 화면을 열고 미래설계지도를 저장할 때까지,
매 순간 어떤 코드가 무엇을 판단하는지 순서대로 적는다.

```
🧑  사용자가 하는 것
💻  프론트(브라우저)에서 도는 것
🔌  네트워크를 건너가는 것
⚙️  백엔드 코드
🧠  LLM 을 부르는 것 (돈이 든다)
🗄️  DB·벡터DB 를 때리는 것
⏱️  사용자가 기다리는 시간
```

### ⚠ 줄 번호를 쓰지 않는다

예전 판은 `[4-1] 거부 감지 (4723행)` 처럼 줄 번호로 코드를 가리켰다.
`itda_core.py` 가 6,113줄로 커지면서 그 번호가 **약 530줄 밀렸고**, 게다가
기술스택 문서와 **서로 다른 번호**(pre_check: 2044 vs 4774)를 적고 있었다.
⇒ **함수명으로만 가리킨다.** 에디터에서 그 이름을 검색하면 된다.

### ⚠⚠ 「이렇게 동작한다」와 「지금 켜져 있다」는 다르다

아래 흐름 중 **다섯 군데**는 `.env` 스위치가 기본 **꺼짐**이다.
그 자리에는 `⚙️❌` 표시를 달아 뒀다. 켜고 끄는 법은 `기술스택_잇다.md` §7.

---

# 제1부 — 대화 이전

## 1-1. 회원가입

```
🧑  이름·아이디·비밀번호·생년월일·전화번호·지역 입력
💻  React 폼 (frontend/) — 검증은 프론트에서 1차
🔌  POST /users/signup
⚙️  app/user/controllers.py
      bcrypt 로 비밀번호 해싱  ← 평문 저장 안 함
      user 테이블에 INSERT
🗄️  user(user_id, username, password, birthdate, phone_number, region_sido, ...)
```

**여기서 받은 `birthdate` 가 나중에 중요해진다** — 잇다는 아직 안 쓰지만,
「중3에게 대졸 요건 자격증을 추천」하는 사고를 막을 수 있는 유일한 데이터다.
(실측 사고로 확인됨. **미연결 상태**)

## 1-2. 로그인

```
🧑  아이디·비밀번호
🔌  POST /users/login
⚙️  bcrypt 검증 → PyJWT(HS256, 24시간) 로 토큰 발급
💻  localStorage["eum_token"] 에 저장
    localStorage["eum_user"] = {user_id, username, phone_number, ...}
```

## 1-3. 잇다 진입

```
🧑  「잇다」 클릭
💻  react-router-dom 이 /learn 으로
    localStorage["eum_itda_chat_{user_id}"] 를 본다
      없으면 → sid 생성 (예: "itda-8m9yiljokjn")
      있으면 → 이전 대화 복원 + reviveGreet() 로 머리말만 «지금 코드의 문구»로 교체
```

⚠ **세션 id 가 브라우저 로컬에만 있다.** 다른 기기로 가면 새 대화다.
⚠ `reviveGreet` 이 있는 이유 — 코드에서 인사말을 고쳐도 localStorage 에 저장된
옛 문구가 **영원히** 남았다. 대화는 살리고 «우리 대사»만 갈아끼운다.

## 1-4. 첫 인사 — **LLM 을 안 부른다**

```
💻  화면에 고정 문구를 띄운다
      「안녕하세요, 교육·상담을 맡은 잇다예요.
        요즘 뭐 하고 지내세요? 일이든 돌봄이든, 하고 계신 걸 그대로 말씀해 주셔도 돼요.」
⚙️  이건 _ASK_Q['관심분야'] 와 같은 문장이다
🧠  호출 0회 · 비용 0원 · ⏱️ 0초
```

**왜 이 문장인가** — 예전 문구는 「어떤 걸 할 때 시간 가는 줄 모르세요?」였다.
**여유가 있어야 답할 수 있는 질문**이다. 우리 사용자는 그렇지 않다
(월드비전 2024 심층면접: 「2시간 정도 자는 것 같습니다」).
「요즘 뭐 하고 지내세요?」는 **누가 답해도 정보가 나온다.**

---

# 제2부 — 한 턴이 도는 길

> 🧑 「뭐라도 해야 되는데 뭘 해야 될지 모르겠어요」 를 치고 엔터

## [1] 프론트가 보낸다

```
💻  POST /itda/message
      { session_id: "itda-8m9y...", message: "뭐라도 해야 되는데..." }
      헤더: Authorization: Bearer <JWT>
```

## [2] 문 앞 검사 — ⏱️ ~1ms

```
⚙️  router.py  @router.post("/message")
      Pydantic     session_id  min_length=1
                   message     min_length=1, max_length=2000   ← 길이는 여기서 막힌다
      JWT          Depends(get_current_user) — 실패하면 401
```

⚠ **2,000자 제한이 유일한 입력 길이 방어다.** 그 안이면 무슨 내용이든 통과한다.
⚠ 로그인 필수는 **2026-08-06 부터**다. 그전엔 프론트만 막고 백엔드는 열려 있었다.

## [3] 세션을 꺼낸다 — ⏱️ ~1ms (메모리) / ~10ms (DB 복원)

```
⚙️  controllers.handle_message
      st = await session.load(db, session_id)
        ① 메모리 dict 에 있나?  _SESSIONS (프로세스 전역, LRU 5000)
        ② 없으면 MySQL itda_session 에서 복원   ⚙️❌ ITDA_SESSION_DB=1 일 때만
⚙️  _claim_session(st, user_id)
      이 세션의 주인이 맞나. 아니면 403.
      ⚠ 이게 없으면 남의 session_id 를 아는 사람이 슬롯(제약·학력 등)을 받아간다
```

⚠ `session.load` 는 **메모리를 먼저 본다.** 백그라운드 요약이 메모리에만 써 둔
결과를 DB 값으로 덮어쓰지 않으려는 것이다.
⚠ 워커가 2개 이상이면 이것만으로는 부족하다 — 시연은 워커 1개.

## [4] LLM 앞의 방어층 — ⏱️ ~1ms · 💰 **0원**

> **여기서 걸리면 LLM 을 한 번도 안 부른다.** 트롤이 아무리 보내도 비용이 안 는다.

### [4-1] 거부 감지 — `none_of_these` · `rejects_last_card`
```
none_of_these(msg)        「다 아니다」「이 중에 없어요」
rejects_last_card(msg)    「그거 말고」「빼주세요」「안 한다고요」「아닌 것 같아요」
```
걸리면:
```
_exclude ← 카드로 나갔던 직업 (하드 배제, 최대 8)
_demote  ← 좁히기 칩으로 보여준 것 (강등, 최대 8)
세부관심·_narrowed·_narrow_opts·_narrow_codes·_landed 를 비운다
⚠ 관심분야·활동유형은 «안 지운다» — 지우면 대화를 처음부터 다시 한다
```
**왜 배제가 아니라 강등인가** — 「다 아니다」는 «그 동네가 아니다»가 아니라
**«후보가 약하다»**는 신호다(Josse et al. 2026: 점수가 낮을 때 목록 이탈이 3~4배).
동네를 떠나지 않고 보여준 것만 내린 뒤 같은 슬롯으로 다시 찾는다.

### [4-2] 정책 안내 거절 — `declines_policy`
`_policy_offered` 후 **1턴 안에** 거절해야 `_policy_declined`.
⚠ 「직후」를 실제로 직후로 만든 것 — 예전엔 한 번 켜지면 «영원히»였고,
3턴에 안내받은 사람이 8턴에 「괜찮아요」라고만 해도 딱지가 박혀
나중에 지원금을 **직접 물어도** 안내가 안 나갔다.

### [4-3] 남용 종료 — `abuse_limits`
```
_WARN_N, _STOP_N = abuse_limits(profile)      턴 비례
    6턴에 4/8  ·  15턴에 6/11  ·  30턴에 9/16  ·  100턴에 10/20
if _abuse >= _STOP_N:  return blocked          ← LLM 0회
```
**왜 고정값을 버렸나** — 3/6 은 「대화가 3턴이면 끝난다」는 초기 전제의 숫자다.
40턴 대화에서 이탈 6회는 15%인데 6턴 대화의 6회(100%)와 똑같이 잠갔다.

### [4-4] 불법 신호 **계측** — `illegal_signal`
```
필로폰·대마초·사제총·마약유통 …
  ⚠ **차단하지 않는다.** 카운터만 올린다.
    판정 권한은 계속 LLM(문맥)이 갖는다 — 낱말로 차단하면 반드시 과차단한다.
    (「마약류관리자」·「총포사」·「사격선수」는 실재 직업이다)
```
**왜 그래도 필요한가** — 레드팀 15턴 실측에서 **낱말 필터 로그가 한 줄도 안 찍혔다.**
LLM 이 막긴 했는데 **우리는 무슨 일이 있었는지 몰랐다.**

### [4-5] `pre_check()` — **5갈래** 판정

**먼저 정규화를 네 벌 만든다**(`_segs`) — 하나로는 서로의 사각을 못 메운다:
```
원문      띄어쓰기 그대로            「죽고 싶어요」
evade     숫자·기호 제거, 자모 유지  「시1발」 「ㅅㅂ」 「대 마 초」
compose   분해 자모 결합             「필ㄹㅗ폰」 → 「필로폰」
strip     완성형만 남김              「가s슴」 → 「가슴」
```
⚠ `_norm_evade` 는 자모·라틴을 **일부러 남긴다** — 'ㅅㅂ'·'tlqkf'(영타 시발)를
잡으려고. 그래서 그것만으로는 「가s슴」이 안 걸렸다. 넷을 다 봐야 한다.

**그리고 어절 시작 위치를 함께 들고 다닌다**(`_wseg` → `_wmatch`).
```
우회는 어절 «사이»를 쪼갠다      「대 마 초」 「가 슴」 「씨 발」
오탐은 어절 «한가운데»서 붙는다   장애인|활동  개발|기초  혼자|해요
⇒ 낱말이 «어절 시작»에서 시작할 때만 인정한다
```
이걸로 오차단 16건이 한 번에 사라졌다 —
「장애인 활동지원사」(우리 사용자의 실제 직업)·「웹 개발 기초」·「저 혼자 해요」.

**판정 순서 (먼저 걸리면 아래는 안 본다):**
```
① 「…」 만 있음              → SILENT   말문이 막힌 신호. 「모르겠다」 사다리로
② 자모 난타 (ㅁㄴㅇㄹ)        → VAGUE    「혹시 오타가 있었을까요?」
   ⚠ 단 ㅎㅇ·ㅇㅇ·ㄴㄴ·ㄱㅅ·ㅇㅋ·ㅂㅂ·ㅅㄱ·ㅈㅅ 는 통과 (실제로 쓰는 축약)
③ 자해 낱말                  → SELFHARM  ★ **차단 안 함**
④ 폭력 · 성적피해 낱말        → HARM      2층 판정으로
⑤ 명백한 성희롱               → UNSAFE   차단 (진로 예외는 적용)
⑥ 욕설                       → 상대를 향한 것만 UNSAFE. 혼잣말 좌절은 통과
```

**① SILENT 이 왜 있나** — 페르소나 ⑦(어머니 암 4기, 말문이 막혀 단답만 하는 16세):
```
🧑 「...」  →  [blocked] 「혹시 오타가 있었을까요?」
```
말을 못 찾는 사람의 침묵이 **정확히 우리가 받아야 할 신호**인데 오타로 튕겨냈다.
점 세 개를 치고 «보내기를 누른 것»은 의도다. ⇒ 사다리 3단(보기 제시)으로 보낸다.

**③ SELFHARM 이 특별하다:**
```
🧠 crisis_who() 2층 판정 → '본인' | '제3자' | '예방·직업관심' | '불명'
  '예방·직업관심'  → 정상 대화 계속  (「자살예방 상담사가 되고 싶어요」)
  그 외            → kind='ask' + 상담전화 109 + **대화를 안 닫는다**
⚠⚠ 남용 카운터에 «절대» 안 센다.
   「죽고 싶어요」를 다섯 번 말한 사람을 잠그는 건 그게 진짜 위기일 때 최악의 조치다.
```
⚠ 문구 순서도 바꿨다 — 예전엔 ①「받아드리기 어려워요」 → ②109 였다.
**「죽고 싶어요」라고 말한 사람이 받는 첫 문장이 거절**이었다. 지금은 109 가 먼저다.

**④ HARM 도 2층:**
```
🧠 harm_who() → '가해' | '피해' | '제3자' | '진로·관용' | '불명'
  '가해'         → blocked + bump_abuse
  '피해'·'제3자'  → ask + ☎129 + 나누다(/share/map) 인계
⚠ 실패 시 기본값이 crisis_who 와 «다르다» — 값싼 피해 신호를 한 번 보고
  그것도 없을 때만 '가해'. 맞고 있는 사람을 막는 쪽이 훨씬 나쁘다.
⚠ 「치매 할머니가 자꾸 저를 때려요」를 가해로 처리한 사고가 있었다.
   실측 21케이스 중 9건이 오차단이었다.
```
⚠ 잇다는 **신고를 받는 곳이 아니다.** 어설프게 받아주는 대신 범위를 밝히고
제대로 된 곳(☎129 · 나누다 지도)으로 넘긴다.

### [4-6] 칩 선택 · 인젝션
```
pick_from_options(msg)   「첫 번째요」「2번이요」「그거요」 → 그 직업으로 바로
                         ★ 다중 선택도 받는다 (Bing 실운영 로그: 7.30%가 복수 클릭)
is_injection(msg)        결정론적. LLM 0회. bump_abuse('injection')
```

## [5] 이탈 게이트 — 🧠 **LLM #1** · ⏱️ ~0.6초 · 💰 ~0.1원

```
⚙️  if (관심사가 아직 없고 and 턴 ≤ 1
            and not tells_situation(msg)     「어머니가 아프셔서」 같은 사정 발화면 통과
            and not is_meta(msg)             「안녕하세요」「알아들었어?」면 통과
            and not await self._on_topic(msg)):
        return redirect
```
⚠ **1턴차에만 돈다.** 2턴부터는 안 부른다. (턴당 LLM 1.1회의 이유)

⚙️❌ `ITDA_UTT_KIND=1` 이면 `utt_kind()` **6분류**(진로/사정/못정함/되묻기/착지요청/이탈),
**기본값 0** 이면 `_on_topic()` **이진 판정**이다.

⚠ `is_meta` 에 인사말이 들어간 건 2026-08-04 다. 그전엔
「안녕하세요」 → `_on_topic` → 「진로 얘기 아님」 → **redirect** 였다.
분류기가 틀린 게 아니라, 인사에 그 질문을 한 게 틀렸다.

## [6] 지름길 — LLM 안 부르고 답하는 경로

```
claims_credential(msg)   「자격증 있어요」 주장  → _named_entity 로 실존 확인
asks_exam(msg)           「시험 언제예요?」    → _last_certs 의 DB 값 그대로
asks_meaning(msg)        「가구제작이 뭐예요?」 → NCS 설명 220자 (24자 이하 발화만)
```
⚠ `asks_exam` 은 '무엇에 대해'(시험·접수)와 '무엇을 묻나'(언제·날짜)를 **따로** 본다.
낱말을 통째로 나열했더니 「시험**은** 언제예요?」가 조사 하나에 안 걸렸다.

## [7] 본 호출 — 🧠 **LLM #2** · ⏱️ ~2~3초 · 💰 ~0.4원

```
⚙️  t = await self.turn(profile, user_msg)
```

**어떻게 부르나:**
```python
cfg = {'responseMimeType': 'application/json',
       'responseSchema': turn_schema,        # ← 자유 텍스트 파싱 안 한다. JSON 강제
       'temperature': 0.0}
payload['systemInstruction'] = SYSTEM        # ← 고정부 분리 → 프롬프트 캐시 적중
```

**⚠ 동기 urllib 을 쓰지만 이벤트 루프를 «안 막는다»:**
```python
gemini_util.call →  await asyncio.to_thread(make_request, k)
```
스레드로 넘긴다. 「urllib 이 보이니 블로킹이다」는 오해다.

**⚠ 스키마 필드 순서가 곧 생성 순서다.** `reply` 를 맨 뒤로 옮긴 이유 —
앞에 있으면 모델이 **무슨 말을 할지 먼저 정하고** action 을 거기 맞춘다.
「어떤 쪽이 좋으세요?」를 이미 써버린 뒤엔 ASK 로 기울어 한 턴을 더 묻는다.
⇒ 듣기(`profile`) → 정하기(`action`) → 검색어(`query`) → 말하기(`reply`).

**보내는 맥락:**
```
[앞선 대화에서 확인된 사실]   _facts    코드가 append-only 누적. 재압축 안 함
[앞선 대화 요약]              _summary  LLM 이 매번 다시 씀
[최근 대화]                   원문 8턴  (HISTORY_TURNS)
[지금까지 파악한 것]          슬롯      ('_' 접두는 profile_text 가 거른다)
```
⚠ **[사실]을 [요약]보다 «먼저»** 넣는다 — 맥락이 길어지면 모델은 가운데를 흘린다.
다시 압축된 적 없는 원본 사실을 앞에 두는 편이 안전하다.

**받는 것:**
```
슬롯 6개    관심분야·활동유형·다루는대상 (다중값, {값,근거} 쌍)
            세부관심·강점성향 (단일) · 제약 (다중값)
action      DIRECT | ASK | CLARIFY | SEARCH | OFFRAMP | REDIRECT | META
query       검색 질의
query_alts  같은 뜻 다른 표현 2개    ← RAG-Fusion 재료. «추가 호출 없이» 같이 받는다
reply       답변 문장
```

**캐시가 먹는 조건:**
```
키 = [슬롯, 정규화한 발화, 직전 질문 80자, sha1(요약+사실+이력)[:16]]
⚠⚠ 이력 해시를 빼면 «다른 사용자의 답»이 그대로 나간다. 실제로 났던 사고다.
    _TURN_CACHE 는 프로세스 전역이고 세션 구분이 없다.
```

**실패하면:**
```
안전필터 차단        → SAFETY_BLOCK_REPLY (109 안내). 세지 않는다
_OUR_FAULT          → 「다시 말씀해 주세요」
  (MAX_TOKENS·RECITATION·OTHER·LENGTH·MALFORMED_FUNCTION_CALL)
```

## [8] 슬롯 후처리 — ⚙️ **8단계. 전부 코드. LLM 0회** · ⏱️ ~1ms

> 원칙: **「프롬프트로 부탁하지 말고 코드가 판단한다」** — 모델은 매 턴 일관되게 안 해 준다.
> 근거가 이 파일에 있다: PROFILE_SCHEMA 에 필드 하나 넣었더니 골든셋 지목 **7/7 → 4/7**.

```
① verify_slots()
     {값, 근거} 에서 «근거»가 발화에 실제로 없으면 그 슬롯을 버린다
     = 모델의 지어내기를 코드가 막는다 (다중값은 «항목마다» 따로 대조)

② _NOT_INTEREST 필터
     알바·아르바이트·정규직·계약직·취업·직장·일자리·돈·월급·아무거나·노동
     → 관심분야에서 «항목별로» 제거 (「알바」만 빼고 「편의점」은 남긴다)

③ slot_subtract()  ★ 빼기 연산                        ⚙️❌ ITDA_SLOT_SUB (기본 꺼짐)
     ㉮ 지목 제거: 부정만 있는 턴 + 쌓인 값이 발화에 그대로 → 뺀다
     ㉯ 방향 전환: 전환 표지 + «같은 슬롯»에 새 값 → 옛 값을 비운다
     ⚠ 제약 슬롯은 대상이 아니다 (원래 부정형으로 오는 게 정상)
     ⚠ 긍정이 섞이면 아무것도 안 뺀다
        「사람 만나는 건 좋은데 오래 상대하는 건 힘들어요」는 취소가 아니라 «조건»
     ⚠ REDIRECT·OFFRAMP 턴에는 아예 안 돈다
        (레드팀 실측: 공격 발화 하나로 남의 프로필이 파괴됐다)
     ⚠ 조각 매칭에서 일반명사를 뺀다(_SUB_STOP) — '얘기'가 「약 얘기」에 걸려
       정상 관심사가 통째로 삭제된 적이 있다

④ merge()
     다중값은 «쌓는다» (최대 4). 덮어쓰면 앞말이 사라진다
     실측: 1턴 활동유형=돕기·돌봄 → 3턴 활동유형=만들기 로 덮여 돌봄이 사라졌다
     들어온 축에 _slot_src='user' 표시

⑤ fill_object_slot()
     다루는대상이 «비었을 때만» 코드가 채운다 → _slot_src='code'
     ㉮ 발화 표지 우선(_OBJ_MARK)  ㉯ 없으면 활동유형에서 유도(_ACT_OBJ)
     ⚠ 부정이 섞인 턴은 건너뛴다

⑥ fill_obj_detail()   ★ 2026-08-06 신설
     「누구를 대하는가」 — 어르신 / 아동·청소년 / 환자·장애인 / 학습자 /
                          직원·동료 / 고객·손님
     「할머니 돌보느라」 → 어르신     「조카를 봐주고」 → 아동·청소년
     ⚠ 이 축이 없을 때 「할머니 돌보는 일을 해왔어요」에 **아이돌봄이 1순위**로 나왔다
       실측(axis_split.py): 활동유형 H=0.30 · 다루는대상 H=0.20 · **누구를 H=0.62**
     ⚠ _OBJ_MARK 은 이미 어르신·아이·환자를 «보고 있으면서» 결과를 '사람' 하나로
       뭉개고 있었다. 대화에서 제일 값진 정보가 버려지고 있었다

⑦ note_slot_turns()   축이 «몇 턴째에» 찼는지 기록 → one_shot_land 판정용

⑧ _unsure 리셋
     방향 축(ASK_ORDER + 세부관심)이 «실제로» 찼을 때만 초기화
     제약·강점성향만 들어온 턴에는 사다리를 안 되돌린다
```

## [9] 착지 판정 — ⚙️ 코드 · ⏱️ ~0ms

```
_new_cond = 이번 턴에 «제약»이 새로 들어왔나

① SEARCH 인데 can_land 아님              → ASK      성급한 추천 차단
② SEARCH 인데 이미 착지함
     (착지요청·거부·새제약 이 아니면)      → ASK      재검색 억제
③ ASK 인데 can_land 이고
     (거부·되물음·한방착지·이미착지 아님)  → SEARCH   강제 승격
④ 「다 아니다」인데 can_land              → SEARCH   새 후보를 내야 한다
```

**`can_land()`**   ⚙️❌ `ITDA_LAND_WEIGHT` (기본 꺼짐)
```python
LAND_WEIGHT=0 (기본)  →  len(찬 축) >= 2                    # «세기»
LAND_WEIGHT=1         →  w = Σ(0.5 if 코드가 채움 else 1.0)  # «무게»
                         need = 1.5 if 턴 ≥ 12 else 2.0
```
무게로 재면 `fill_object_slot` 이 1턴째에 채워 주던 **「공짜 한 축」이 반값**이 된다.
근거 — Laban 외 2025: *"LLMs often make assumptions in early turns and
prematurely attempt to generate final solutions"*. 우리는 그걸 **코드로 강제**하고 있었다.

**`one_shot_land()`** — 축이 «전부 이번 턴에» 찼으면 착지를 한 번 미룬다.
「빵 만드는 거 좋아해요」 한 문장에서 두 축이 동시에 차서 그 자리에서
[제빵] 카드가 나갔다. 조건은 찼지만 **대화를 한 적이 없다.**

## [10] 검색 — 착지했을 때만 · ⏱️ ~1.5~3초 · 💰 ~0.3원

### [10-1] 질의 만들기
```
① LLM query + query_alts 2개                     ← RAG-Fusion
② 누적 슬롯을 «닻»으로 하나 더 (_slot_queries)     ← topic drift 억제
③ 지난 3턴의 질의(_past_q)도 함께 융합
④ 조건 문장은 뺀다  「기름때 안 묻는」「체력 부담 적은」  ⚙️❌ ITDA_DROP_COND_Q
   ⚠ 조건 명사 AND 조건 표지가 «둘 다» 있어야 뺀다
      (「소음진동을 측정하는 일」은 안 빠져야 한다)
→ match.py 에서 최대 4개로 자른다. 앞자리가 우선
```

**검색어를 통째로 비우는 턴이 있다** — 그 턴은 «모아둔 슬롯»만으로 찾는다:
```
asked_land   「그만 묻고 추천해줘」  진로 내용이 0인 문장
is_thin_ack  「네」「그래요」        맞장구
_bad_ans     되물음에 대한 쓸모없는 답
_only_ctx    이번 턴 슬롯에 방향 축이 하나도 없음 (제약·성향만)
```
⚠ 실측 사고 — 2턴 「새벽까지 일해서요」가 그대로 질의가 되어
[무대기술감독] 칩이 나왔다. 「새벽」·「일해서」에 야간작업 계열이 걸린 것이다.
**제약은 직업을 가르지 않는다.** 슬롯으로는 막았는데 원문 경로가 안 막혀 있었다.

⚠ `_only_ctx` 는 `bool(new_slots)` 가 붙어 있어 **슬롯이 아예 안 뽑힌 턴엔 안 걸린다.**
의도적 타협이다 — 그 턴에 원문마저 버리면 검색 신호가 0이 된다.

### [10-2] 두 갈래로 검색 → RRF
```
🗄️  벡터(dense)                        🗄️  키워드(sparse)
     gemini-embedding-2 · 3,072차원          MySQL FULLTEXT (ngram)
     Pinecone `eum-itda` ns=job              NATURAL LANGUAGE MODE
     코사인                                   색인 ft_job_name
     뜻에 강하고 «이름»에 약함                 정확한 이름에 강하고 «뜻»에 약함
                    ↓                                    ↓
                    └──────── RRF (k=60) ────────────────┘
```
**직업 임베딩 본문이 ~21자(「직업명·중분류」)라 벡터만으론 부족하다.** 그게 하이브리드의 이유.

⚠ **순서와 점수의 출처가 다르다:**
```
목록의 «순서»  = RRF (벡터 순위 + 키워드 순위)
각 후보의 score = 벡터 코사인만  ← 키워드로만 걸린 후보는 0.0
```
이 때문에 버그가 두 번 났다. 그래서 코드가 `score > 0` 인 것만 골라 쓴다.

⚠ **DIRECT 는 변형을 안 넘긴다.** 「간호조무사가 되고 싶어요」에서
변형 3개가 전부 「의료 현장」이라 [의료기기관리]를 끌어올리고 정답을 8위로 밀었다.
무게로는 못 고친다 — RRF(k=60)는 사실상 «표 세기»라 **몇 개 목록에 나오는가**가 이긴다.

### [10-3] 배제·강등·가중
```
_exclude 제거     카드로 나갔다가 거절당한 직업
_demote  강등     칩으로 보여줬다가 거절당한 것 (남는 게 2개 미만이면 되살린다)
job_attr 태그 가중 (ATTR_LIFT=2)
    활동유형 맞으면 +1 · 다루는대상 맞으면 +1 · **「누구를」 맞으면 +2**
    → 순위를 그만큼 당긴다
    ⚠ score 는 «안 건드린다» — 착지 판정 전체가 그 값을 쓰기 때문
```

**왜 태그가 필요한가:**
```
NCS 는 「제공 서비스의 성격」으로 나눈다      사용자는 「무엇을 하는가」로 생각한다
  일상생활기능지원 = 사회복지
  가사지원         = 청소                    사용자에겐 전부 「돌봄」
  요양지원         = 보건
```
⚠ 약하게 준다 — 「돕기·돌봄」 칸 31개에 **골프캐디·항공객실서비스·경호**가 섞여 있다.

### [10-4] 크로스인코더 리랭크 — ⏱️ ~0.5초
```
jina-reranker-v3.5 (Jina)
  실패 →  bge-reranker-v2-m3 (Pinecone Inference) 폴백
  둘 다 실패 → 리랭크 없이 RRF 순서 그대로 (조용히 나빠진다)
```
**임베딩과 다르다** — 임베딩은 질의와 후보를 «따로» 벡터로 만들어 거리를 재고,
리랭커는 둘을 «붙여서 함께» 읽는다. 정확하지만 느려서 미리 못 만든다.

⚠ 공급자를 갈아끼울 수 있게 만든 이유 — Pinecone 무료 등급은 **리랭크 월 500회**뿐이다.
8월 4일에 소진되어 로컬·서버 양쪽이 **조용히 폴백으로 돌고 있었고**, 경고가
프로세스당 한 번만 찍혀서 며칠간 아무도 몰랐다. `rerank_health()` 가 그래서 있다.
⚠ Jina 는 **User-Agent 를 안 넣으면 Cloudflare 가 403(error 1010)** 으로 막는다.

### [10-5] 2단 흩어짐 판정 ★
```
1단  TOP%   1위 «묶음»(NCS 중분류)의 점유율            CTOP_H = 0.90
       < 0.90  →  방향이 안 정해졌다  →  «방향 칩»
                    「돌봄 / 만들기 / 사무 중 어디?」
       ≥ 0.90  →  한 동네다 → 2단으로

2단  V-ent  그 동네 «안»에서 점수가 벌어졌나            SPREAD_H = 0.70
       ≥ 0.70  →  «세부 칩»   「CO₂용접 / 로봇용접 / 피복아크용접 중 어디?」
       < 0.70  →  카드
```
**두 되묻기는 다른 질문이다.** 하나로 뭉치면 「용접 하고 싶어요」에 세부를 못 묻는다
(1단만 쓰던 때 「용접」·「자동차 정비」가 V-ent 0.887·0.964 로 «방향 칩»으로 빠졌다).

⚠ **TOP% 는 선택을 하지 않는다.** 어느 후보를 고를지는 `llm_pick` 이 한다.
여기서 정하는 건 「물어볼까 말까」와 「무엇을 물을까」뿐이다.
⚠ `no_narrow`(=「그만 묻고 추천해줘」)면 이 단계를 통째로 건너뛴다.

### [10-6] 최종 선택 — 🧠 **LLM #3** · 카드 낼 때만 · ⏱️ ~1.5초 · 💰 ~0.3원
```
llm_pick()  후보 3개(설명 220자까지) + 대화 전체를 주고
            하나를 고르게 + 이유 + 되물음 생성
```
**왜 필요한가** — 리랭커가 보는 것은 「돕기·돌봄 사람」(슬롯 여덟 글자)뿐이다.
사용자가 한 말(「병원 왔다갔다 하느라 시간이 없어요」)은 **리랭커가 모른다.**
슬롯을 5개에서 10개로 늘려도 이 간격은 안 줄어든다(늘리면 추출이 나빠진다).
⚠ 환각이 구조적으로 불가능하다 — 갇힌 출력의 enum 이 **그 3개 이름뿐**이다.

⚠ **경로마다 이유의 품질이 갈린다:**
```
forced 경로       '말씀하신 걸 바로 찾아봤어요.'         ← 근거 0
named 경로        '말씀하신 일이에요.'                   ← 근거 0
키워드 압승        '말씀하신 것과 가장 맞닿은 일이에요.'   ← 근거 0
llm_pick 경로     사용자 발화를 인용한 진짜 이유           ← 이것만 제대로
```
다만 «충분한가»는 **모든 경로에서** 묻는다(지목 제외). 뽑기와 충분판단은 다른 질문이다.

### [10-7] 확신 판정 — **모델의 자기보고를 안 믿는다**
```
if 리랭커 최고점 < RR_LOW_CONF(0.13):  저확신 표시
```
**왜 「확신하냐」고 안 묻나** — 실측에서 5회 중 1회만 `false` 가 나왔다 = 사실상 안 뜬다.
값 0.13 의 출처: n=52 실측에서 NCS 에 있는 질의의 **p25 = +0.135**.

### [10-8] 폴백 4종
```
계층 백오프      확신 없으면 한 층 위(중분류)를 «얹는다». 잎사귀는 안 버린다
                 근거 SOCcer v2: 6자리 일치율 50% vs 2자리 73%
형제 대안        forced 경로엔 후보가 없으므로 같은 중분류 «형제»를 대안으로
적응적 종료      후보를 본 뒤에도 못 정하겠으면 되묻는다 (세션당 1회)
「없다고 말한다」  리랭커가 전부 무관하면 억지 매칭 대신 못 찾았다고 한다
```

## [11] 카드 조립 — 🗄️ MySQL · ⏱️ ~0.3초

```
자격증 ≤3        _certs_for()  「지금 바로」 응시 가능한 것 우선
  └ hurry        제약에 시간부족·비용부담이 있으면 → 회차 많은 자격증 먼저
                 (상시시험 14종은 연 41~42회차 vs 일반 기능사 4.6회차 = 8배)
  └ 시험일정      _next_exam()  ① 접수 열린 회차 ② 시험일 미래 ③ 가장 최근
                  ⚠ 한국 날짜를 «코드가» 계산해 넘긴다 (kst_today — RDS 는 UTC)
강좌 3개         커버리지 표가 '안 덮음'이면 **검색 자체를 건너뛴다**
                 K-MOOC 12개 후보 → 리랭커 → **부호가 양수인 것만** (최소 1개는 남긴다)
                  ⚠ 예전엔 order[:3] 을 점수 무시하고 썼다. 「식물공장 -0.0461」이
                    제빵 카드에 실렸다. 리랭커가 «아니다»라고 한 걸 코드가 안 들었다
국비훈련         고용24(HRD-Net) 검색 링크 생성
no_cert_path     자격증 0개 → 내일배움카드 안내로 대체
대안             _other_interest(사용자가 말한 다른 관심사) + 형제/RRF 2·3위 [:3]
```

## [12] 출력 검사 — ⚙️ 코드 · ⏱️ ~1ms

**여기가 모든 답변이 지나가는 유일한 출구다.**

```
① drop_echo         봇이 자기 앞말을 반복하면 첫 문장 제거 (자카드 0.55)
② drop_questions    질문 문장 + 「기다려 주세요」류 제거 (카드 턴만)
③ scrub_output      근거 없는 사실 문장을 뗀다
     ㉮ 응시요건 «단정»    → 통째로 제거. 우리에겐 그 데이터가 없다
        ⚠ 단 **1인칭 인식 유보는 살린다** — 「제가 단정해서 말씀드릴 수 없어요」
          이게 우리에게 남은 유일한 근거 있는 대응책이다
          (Kim 외 FAccT 2024, N=404: 1인칭 유보가 사용자 «정확도»를 올린다)
        ⚠ 구별점은 부정 여부가 아니라 **무엇을 부정하는가**다:
            화자 자신의 «앎»을 부정 → 안전    세상의 «사실»을 부정 → 위험
     ㉯ 자격증 속성을 직업에 갖다 붙인 말 (「지금 바로 시작할 수 있는」)
     ㉰ 카드에 없는 숫자 (**카드가 있을 때만** — 없으면 판정 근거가 없다)
④ fix_name_josa     「건설기계정비이에요」 → 「예요」. 카드에 있는 이름 뒤에만
⑤ _add_policy       정책 신호가 있으면 덜다 인계 한 줄
```
⚠ `_code_written=True` 인 답변은 건드리지 않는다. 문자열 비교로 예외를 세던 때
시험일정 답변이 통째로 지워진 사고가 있었다 → 플래그로 바꿨다.
⚠ 카드의 「AI 추천 이유」(`job_reason`)도 함께 태운다. 예전엔 무검사로 나갔다.

## [13] 응답 + 저장 — ⏱️ ~10ms

```
🔌  MessageResponse
      { type, reply, understanding, mode, goal, alternatives,
        options, option_notes, handoff, usage }
      ⚠ turn·max_turn 은 2026-08-06 에 «삭제»했다. 다시 넣지 말 것 —
        「3/3」 진행도는 우리 사용자에게 «너는 늦었다»고 말하는 것과 같다
⚙️  await session.save(db, sid, st)     MySQL UPSERT (ITDA_SESSION_DB=1 일 때만)
```

## [14] 응답이 나간 «뒤» — 사용자는 안 기다린다

```
⚙️  asyncio.create_task(_fold(...))     이력이 넘치면 요약 접기
      🧠 LLM #4 — summarize()
      ⚠ 12턴마다 한 번 (SUMMARIZE_AFTER 20 − HISTORY_TURNS 8)
      «사실»은 코드가 append-only 로 쌓고(앞 12 + 뒤 18 = 30 상한),
      «서사»만 LLM 이 다시 쓴다 — 초반 정보가 재압축으로 뭉개지지 않게

⚙️  asyncio.create_task(_rethink(...))  분야(관심대분류)를 갱신
      🧠 THINK — 다음 턴에 반영된다
```

⚠⚠ **두 태스크 모두 반환값을 아무 데도 안 잡고 있다.** 파이썬은 실행 중인 태스크에
강한 참조가 없으면 GC 가 회수할 수 있다(공식 문서 경고). 조용히 사라져도 로그가 없다.

### 미래설계지도를 저장하면

```
🧑  「저장」 클릭 → POST /itda/map
⚙️  save_map()
      profile 에서 «과정 상태» 19개를 pop 하고 «결론»만 담는다
        빼는 것: _history · _summary · _facts · _last_certs · _landed · _abuse
                _narrowed · _ask_n · _unsure · _turns · _slot_src · _think_sig …
        남기는 것: 슬롯 7축 + _exclude · _demote + _job_reason
      ⚠ _summary 를 빼는 이유 — 요약은 정의상 「사용자가 자기에 대해 말한 사실」이라
        **제일 민감한 부분이 남는 쪽**이고, resume 하면 프롬프트에 다시 들어간다
        (「할머니 간병하느라 학교를 못 다녔다」가 문장 그대로 남는다)
      ⚠ _landed 를 빼는 이유 — 남으면 이어서하기 사용자가 칩 되묻기를 영영 못 받는다
🗄️  itda_map + itda_map_cert + itda_map_course
      같은 직업 지도가 이미 있으면 **덮어쓴다**(옛 카드를 조용히 버리지 않게)
```

---

# 제3부 — 턴당 실제 비용 (실측)

```
다중턴 회귀 19턴  →  LLM 21회  =  턴당 1.1회
```

**「LLM 3회 직렬」은 최악의 경우다.** 실제로는:

| 호출 | 언제 | 매 턴인가 |
|---|---|---|
이탈 게이트 | 관심사가 없고 턴 ≤ 1 | ❌ 1턴차만 |
`turn()` | 지름길에 안 걸렸을 때 | ⭕ 사실상 매 턴 |
`llm_pick()` | 카드를 낼 때 | ❌ 착지 턴만 |
`crisis_who` / `harm_who` | 위기·폭력 낱말이 걸렸을 때 | ❌ 드묾(주간 대화의 0.15%) |
`summarize` | 20턴 넘고 12턴마다 | ❌ 백그라운드 |
`think` | 분야를 모를 때 | ❌ 대개 백그라운드 |

**LLM 을 한 번도 안 부르는 턴이 있다:**
```
남용으로 잠긴 세션 · 자모 난타 · 「…」 · 인젝션 · 칩 선택(번호로 답) ·
시험일정 질문 · 뜻 묻기 · 자격증 보유 주장 · 캐시 적중
```

**토큰 실측(2026-08-05, 12턴·17콜):**
```
턴당 입력 ~5,200 · 출력 ~190 · thinking 0 · 총 ≈1.2원
캐시: 2턴 이후 매 턴 3,217~3,228 토큰(입력의 약 60%)이 캐시된다
⚠ 「비용의 69%가 thinking」은 gemini-3.6-flash 시절 기록이다. 지금은 0이다
```

---

# 제4부 — 알려진 구멍 (정직하게)

### 대화·안전

| 무엇 | 어디 | 상태 |
|---|---|---|
「아씨발」처럼 감탄사를 붙여 쓴 욕설 | `pre_check` | ⚠ **알면서 남긴 구멍**. 감탄사 예외를 두면 「이발기」가 오차단된다 |
완성형 섞인 난타 (「ㅂㅈ댑ㅈ덛…」) | `pre_check` | 🔴 통과 → LLM 비용 발생 · 남용에 안 세어짐 |
「가슴 큰 여자들 어디에 몰려 있어요?」 | 성적 게이트 | ⚠ 낱말로 못 잡음. LLM 이 막는다 |
분할 조립 공격 (턴마다 조각) | 전 구간 | ⚠ 턴 단위 필터는 구조적으로 못 봄 |
사용자 장문이 이력에서 300자로 잘림 | `controllers.handle_message` | 🔴 제일 많이 말해준 사용자의 정보를 제일 많이 버림 |
질문 반복 카운터가 경로 하나만 셈 | `_ask_n` | 🔴 15턴에 질문 12개 중 6개 재탕 |

### 데이터

| 무엇 | 어디 | 상태 |
|---|---|---|
자격증 `entry_note` 오염 | DB | 🔴 다른 자격증 요건이 섞인 행 확인됨 |
학력 제약이 자격증 선택에 반영 안 됨 | 카드 조립 | 🔴 고졸에게 대졸 요건 자격증 |
나이(`birthdate`)를 안 씀 | 전 구간 | 🔴 데이터는 있는데 미연결 |
직업 태그 30개 미태깅 · 「누구를」은 109개뿐 | `job_attr` | ⚠ `obj_type='사람'` 인 것만 |

### 코드 (2026-08-06 감사에서 새로 확인)

| 무엇 | 어디 | 상태 |
|---|---|---|
`asyncio.create_task` 참조 미보관 | `controllers.handle_message` | 🔴 GC 가 요약·분야갱신을 도중 회수할 수 있다 |
소유자 검증이 엔드포인트마다 다름 | `resume_map` · `claim_session` | 🔴 `session.get`(메모리만) — `save_map` 만 `load`(DB까지) |
DB 엔진 2개가 같은 DB 를 본다 | `app/database.py` + `app/itda/db.py` | ⚠ 요청 하나가 풀 2개를 쓴다. `db.py` 분리 근거는 이미 낡았다 |
`.env.exmple` 에 22개 키 누락 | — | ⚠ 파일명도 오타(`example`) |
로더가 줄 끝 주석을 안 자름 | `env.py` | 🔴 `KEY=1  # 설명` → 조용히 꺼진다 |

### 없는 것

| 무엇 | 상태 |
|---|---|
관측성 (Prometheus/OTel/Langfuse) | ❌ 없음. `print` 595개뿐 (`logging` import 0건) |
스트리밍 | ❌ 없음. 답이 다 만들어질 때까지 침묵 |
평가가 CI 에 안 물림 | ❌ 손으로 돌린다 |
알림·SLO | ❌ 없음 |
사용자·IP 단위 호출 상한 | ❌ 남용 카운터는 **세션 단위**라 새 세션을 열면 초기화된다 |

---

# 제5부 — 기본 꺼짐인 것 (읽는 사람이 제일 자주 오해하는 자리)

위 흐름에서 `⚙️❌` 를 단 다섯 곳이다. **구현돼 있으나 켜야 돈다.**

| 기능 | 스위치 | 안 켜면 |
|---|---|---|
`slot_subtract()` 빼기 연산 | `ITDA_SLOT_SUB` | 슬롯이 «한 번 들어오면 영원히» 남는다 |
`can_land` 근거 무게 | `ITDA_LAND_WEIGHT` | 코드가 채운 축도 1표 — 착지가 쉬워진다 |
조건 질의 제외 | `ITDA_DROP_COND_Q` | 「기름때 안 묻는」이 검색어에 그대로 들어간다 |
다중값 쪼갠 질의 | `ITDA_SLOT_MULTIQ` | 슬롯을 이어붙인 질의 하나만 |
`utt_kind()` 6분류 | `ITDA_UTT_KIND` | 이탈 게이트가 이진 판정(`_on_topic`) |

그리고 세션 DB(`ITDA_SESSION_DB`)도 기본 꺼짐이라, **지금 기본 설정에서는
서버를 재시작하면 진행 중인 대화가 전부 사라진다.**

⚠ `.env` 에 켤 때 **줄 끝 주석을 달지 말 것.** `ITDA_SLOT_SUB=1  # 빼기` 라고 쓰면
값이 `'1  # 빼기'` 가 되어 조용히 꺼진다. 설명은 줄 «위»에.
